<!--Footer-->
<footer class="page-footer center-on-small-only" id="credits">

<!--Footer Links-->
<div class="container-fluid">
<div class="row">

<!--First column-->
<div class="col-md-6 col-sm-6 col-xs-6">
<h5 class="title">Sources</h5>
<ul>
<li><a href="http://www.rollingstone.com/music/artists/linkin-park/biography" target="_blank">Bio</a></li>
<li><a href="https://en.wikipedia.org/wiki/Hybrid_Theory" target="_blank">Hybrid Theory</a></li>
<li><a href="https://en.wikipedia.org/wiki/Meteora_(album)" target="_blank">Meteora</a></li>
<li><a href="https://en.wikipedia.org/wiki/Minutes_to_Midnight_(Linkin_Park_album)" target="_blank">Minutes to Midnight</a></li>
</ul>
</div>
<!--/.First column-->

<!--Second column-->
<div class="col-md-6 col-sm-6 col-xs-6">
<div class= "right-side-source">
<ul>
<li><a href="https://en.wikipedia.org/wiki/A_Thousand_Suns" target="_blank">A Thousand Suns</a></li>
<li><a href="https://en.wikipedia.org/wiki/Living_Things_(Linkin_Park_album)" target="_blank">Living Things</a></li>
<li><a href="https://en.wikipedia.org/wiki/The_Hunting_Party_(album)" target="_blank">The Hunting Party</a></li>
<li><a href="https://en.wikipedia.org/wiki/One_More_Light" target="_blank">One More Light</a></li>
</ul>
</div>
</div>
<!--/.Second column-->
</div><!-- close row -->
<div class="row">
<!-- Our names -->	
<div class="col-md-12 col-sm-12 col-xs-12">
<div class="credits">
<p>CSC 174 Project 8 Team Shanghai</p>
<p>© 2017 Copyright: Michelle Bushoy, Jerry Dai, Philip Kallinos, Daniella Bloom </p>
</div>
</div>
<!--/.Our names -->
</div><!-- close row -->
</div>
<!--/.Footer Links-->

</footer>
<!--/.Footer-->


</div><!-- close container class -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>        

</body>
</html>
