<!-- Basic Info -->

<h2>Survey: Basic Information</h2>

<div class="form-group">
<div class="col-md-6 mb-3">
<label for="name">First Name:</label>
<input type="text" class="form-control" name="first" id="firstname" required>
</div>
</div>

<div class="form-group">
<div class="col-md-6 mb-3">
<label for="name">Last Name:</label>
<input type="text" class="form-control"  name="last" id="lastname" required>
</div>
</div>

<div class="form-group">
<div class="col-md-6 mb-3">
<label for="email">Email:</label>
<input type="email" class="form-control" name="email" id="email" required>
</div>
</div>

<!-- End Basic Info -->

<!-- Favorite Album -->
<h2>Which Linkin Park album is your favorite?</h2>

<div class="col-md-6 mb-3">
<input type="radio" name="favorite-album" id="hybrid-radio" value="hybrid">
<label for="hybrid-radio">Hybrid Theory</label>
</div>

<div class="col-md-6 mb-3">
<input type="radio" name="favorite-album" id="meteora-radio" value="meteora">
<label for="meteora-radio">Meteora</label>
</div>

<div class="col-md-6 mb-3">
<input type="radio" name="favorite-album" id="minutes-radio" value="minutes">
<label for="minutes-radio">Minutes to Midnight</label>
</div>

<div class="col-md-6 mb-3">
<input type="radio" name="favorite-album" id="thousand-radio" value="thousand">
<label for="thousand-radio">A Thousand Suns</label>
</div>

<div class="col-md-6 mb-3">
<input type="radio" name="favorite-album" id="living-radio" value="living">
<label for="living-radio">Living Things</label>
</div>

<div class="col-md-6 mb-3">
<input type="radio" name="favorite-album" id="hunting-radio" value="hunting">
<label for="hunting-radio">The Hunting Party</label>
</div>

<div class="col-md-6 mb-3">
<input type="radio" name="favorite-album" id="light-radio" value="light">
<label for="light-radio">One More Light</label>
</div>

<!-- End Favorite Album -->

<!-- Songs Section -->
<h2>Which Linkin Park songs do you like?</h2>

<div class="col-md-6 mb-3">
<input type="checkbox" name="crawling-check" id="crawling-check" value="crawling">
<label for="crawling-check">Crawling</label>
</div>

<div class="col-md-6 mb-3">
<input type="checkbox" name="intheend-check" id="intheend-check" value="intheend">
<label for="intheend-check">In the End</label>
</div>

<div class="col-md-6 mb-3">
<input type="checkbox" name="faint-check" id="faint-check" value="faint">
<label for="faint-check">Faint</label>
</div>

<div class="col-md-6 mb-3">
<input type="checkbox" name="numb-check" id="numb-check" value="numb">
<label for="numb-check">Numb</label>
</div>

<div class="col-md-6 mb-3">
<input type="checkbox" name="what-check" id="what-check" value="what">
<label for="what-check">What I've Done</label>
</div>
<!-- End Songs -->

<!-- Favorite Song -->
<h2>Which song is your favorite?</h2>

<div class="col-md-6 mb-3">
<input type="radio" name="favorite-song" id="crawling-radio" value="crawling">
<label for="crawling-radio">Crawling</label>
</div>

<div class="col-md-6 mb-3">
<input type="radio" name="favorite-song" id="intheend-radio" value="intheend">
<label for="intheend-radio">In the End</label>
</div>

<div class="col-md-6 mb-3">
<input type="radio" name="favorite-song" id="faint-radio" value="faint">
<label for="faint-radio">Faint</label>
</div>

<div class="col-md-6 mb-3">
<input type="radio" name="favorite-song" id="numb-radio" value="numb">
<label for="numb-radio">Numb</label>
</div>

<div class="col-md-6 mb-3">
<input type="radio" name="favorite-song" id="what-radio" value="what">
<label for="what-radio">What I've Done</label>
</div>
<!-- End Favorite Song -->

<!-- Why Favorite -->
<div class="form-group">
<div class="col-md-6 mb-3">
<label for="message">Why is this song your favorite?</label>
<br>
<textarea name="message" class="form-control" id="message"></textarea>
</div>
</div>
<!-- End Why Favorite -->

<!-- Submit Button -->
<div class="col-md-6 mb-3">
<input type="submit" name="submit" class="btn btn btn-primary" id="submit" value="Submit">
</div>